# Generated by Django 5.2.17 on 2026-09-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='javascript_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
