# Generated by Django 5.2.17 on 2026-08-20 10:12

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('received', 'Recibida'), ('processing', 'Procesando'), ('graded', 'Corregida'), ('infra_error', 'Error del corrector')], default='received', max_length=20)),
                ('is_late', models.BooleanField(default=False)),
                ('auto_score', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('feedback', models.TextField(blank=True)),
                ('files_digest', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='learning.activityversion')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='learning.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('student', 'assignment', 'attempt_number'),
            },
        ),
        migrations.CreateModel(
            name='GradeOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_score', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('new_score', models.DecimalField(decimal_places=5, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('10'))])),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_overrides_made', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_overrides', to='grading.submission')),
            ],
        ),
        migrations.CreateModel(
            name='GradeCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_score', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('manual_score', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('auto_weight', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=5)),
                ('manual_weight', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5)),
                ('formula_version', models.CharField(default='grade-v1', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('ready', 'Lista'), ('published', 'Publicada'), ('retracted', 'Retirada'), ('pending_review', 'Pendiente de revisión')], db_index=True, default='draft', max_length=20)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('teacher_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('activity_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_calculations', to='learning.activityversion')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grade_calculations_made', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_calculations', to='grading.submission')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(max_length=64)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='grading.submission')),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluator_version', models.CharField(default='static-v1', max_length=30)),
                ('status', models.CharField(choices=[('passed', 'Completada'), ('failed', 'Con fallos'), ('infra_error', 'Error del corrector')], max_length=20)),
                ('passed_points', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=8)),
                ('total_points', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=8)),
                ('score', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('activity_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_runs', to='learning.activityversion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_runs', to='grading.submission')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_case_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('type', models.CharField(max_length=80)),
                ('passed', models.BooleanField(default=False)),
                ('status', models.CharField(default='failed', max_length=20)),
                ('points', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=8)),
                ('earned_points', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=8)),
                ('feedback', models.TextField(blank=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('position', models.PositiveIntegerField(default=0)),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='grading.testrun')),
            ],
            options={
                'ordering': ('position', 'name'),
            },
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['assignment', 'student', '-submitted_at'], name='grading_sub_assignm_645337_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student', 'attempt_number'), name='uniq_submission_attempt'),
        ),
        migrations.AddIndex(
            model_name='gradecalculation',
            index=models.Index(fields=['submission', 'status'], name='grading_gra_submiss_693335_idx'),
        ),
        migrations.AddConstraint(
            model_name='submissionfile',
            constraint=models.UniqueConstraint(fields=('submission', 'path'), name='uniq_submission_file'),
        ),
    ]
