# Generated by Django 5.2.17 on 2026-08-20 10:12

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=180)),
                ('kind', models.CharField(choices=[('lesson', 'Lección'), ('code', 'Código'), ('project', 'Proyecto')], default='code', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicada'), ('closed', 'Cerrada'), ('archived', 'Archivada')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('module', 'title'),
            },
        ),
        migrations.CreateModel(
            name='ActivityVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('instructions', models.TextField(blank=True)),
                ('objectives', models.JSONField(blank=True, default=list)),
                ('learning_outcomes', models.JSONField(blank=True, default=list, help_text='Códigos RA del currículo que aborda la actividad.')),
                ('assessment_criteria', models.JSONField(blank=True, default=list, help_text='Códigos CE del currículo que aborda la actividad.')),
                ('professional_module_code', models.CharField(default='0228', max_length=20)),
                ('curriculum_scope', models.CharField(blank=True, default='Navarra', max_length=80)),
                ('curriculum_unit', models.CharField(blank=True, default='', max_length=80)),
                ('curriculum_source', models.URLField(blank=True, default='https://www.educacion.navarra.es/documents/27590/558252/DF%2B109_2024%2Bmodificacion%2BGM.pdf/6641c899-fd0f-89e3-83f4-aa30c8224707', max_length=500)),
                ('starter_files', models.JSONField(blank=True, default=dict)),
                ('reference_solution', models.JSONField(blank=True, default=dict)),
                ('grading_mode', models.CharField(choices=[('feedback_only', 'Solo feedback'), ('automatic_static', 'Automática estática'), ('manual', 'Manual'), ('hybrid', 'Híbrida'), ('automatic_sandboxed', 'Automática aislada (futura)')], default='feedback_only', max_length=30)),
                ('auto_weight', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('manual_weight', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='learning.activity')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_versions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('activity', '-version_number'),
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for', to='learning.activityversion'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_override', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicada'), ('closed', 'Cerrada'), ('archived', 'Archivada')], db_index=True, default='draft', max_length=20)),
                ('opens_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('max_attempts', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('attempt_policy', models.CharField(choices=[('best', 'Mejor'), ('latest', 'Último'), ('average', 'Media'), ('latest_before_due', 'Último antes de fecha límite')], default='best', max_length=30)),
                ('weight', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('allow_late', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='learning.activity')),
                ('activity_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='learning.activityversion')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohorts', to='learning.academicyear')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AssignmentCohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cohort_links', to='learning.assignment')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_links', to='learning.cohort')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('files', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drafts', to='learning.activityversion')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drafts', to='learning.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drafts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='learning.cohort')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('weight', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='learning.course')),
            ],
            options={
                'ordering': ('course', 'position', 'title'),
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='learning.module'),
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Rúbrica', max_length=180)),
                ('activity_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rubric', to='learning.activityversion')),
            ],
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('position', models.PositiveIntegerField(default=0)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criteria', to='learning.rubric')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='learning.cohort')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('type', models.CharField(max_length=80)),
                ('definition', models.JSONField(default=dict)),
                ('points', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('visibility', models.CharField(choices=[('public', 'Público'), ('private', 'Privado')], default='public', max_length=10)),
                ('feedback', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('activity_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_cases', to='learning.activityversion')),
            ],
            options={
                'ordering': ('position', 'name'),
            },
        ),
        migrations.AddConstraint(
            model_name='activityversion',
            constraint=models.UniqueConstraint(fields=('activity', 'version_number'), name='uniq_activity_version'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status', 'due_at'], name='learning_as_status_d3b6de_idx'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.UniqueConstraint(fields=('academic_year', 'name'), name='uniq_cohort_year_name'),
        ),
        migrations.AddIndex(
            model_name='assignmentcohort',
            index=models.Index(fields=['cohort', 'assignment'], name='learning_as_cohort__55092b_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignmentcohort',
            constraint=models.UniqueConstraint(fields=('assignment', 'cohort'), name='uniq_assignment_cohort'),
        ),
        migrations.AddIndex(
            model_name='draft',
            index=models.Index(fields=['student', 'updated_at'], name='learning_dr_student_e09de5_idx'),
        ),
        migrations.AddConstraint(
            model_name='draft',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='uniq_draft_student_assignment'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'active'], name='learning_en_student_29e9a2_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['cohort', 'active'], name='learning_en_cohort__00ef59_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('cohort', 'student'), name='uniq_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('course', 'position'), name='uniq_module_position'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(fields=('module', 'slug'), name='uniq_activity_module_slug'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(fields=('cohort', 'teacher'), name='uniq_teaching_assignment'),
        ),
        migrations.AddConstraint(
            model_name='testcase',
            constraint=models.UniqueConstraint(fields=('activity_version', 'name'), name='uniq_test_name_version'),
        ),
    ]
