# Generated by Django 5.2.17 on 2026-08-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityversion',
            name='curriculum_edition',
            field=models.CharField(blank=True, default='navarra-2025', max_length=80),
        ),
    ]
