# Generated by Django 5.2 on 2026-08-30.

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_activityversion_curriculum_edition"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityversion",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "Inicial"),
                    ("intermediate", "Intermedia"),
                    ("advanced", "Avanzada"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="activityversion",
            name="hints",
            field=models.JSONField(blank=True, default=list, help_text="Pistas progresivas para el alumnado."),
        ),
        migrations.AddField(
            model_name="activityversion",
            name="language",
            field=models.CharField(
                choices=[("web", "HTML/CSS/JavaScript"), ("bash", "Bash")],
                default="web",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="activityversion",
            name="xp_reward",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Experiencia máxima de la actividad; no es una calificación académica.",
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)],
            ),
        ),
    ]
