# Generated by Django 5.2.17 on 2026-09-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_cohort_track_active_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='web_stage',
            field=models.CharField(blank=True, choices=[('html_css', 'HTML y CSS'), ('javascript', 'JavaScript')], db_index=True, default='', help_text='Etapa del itinerario Web. Déjala vacía para cursos de otros itinerarios o contenido histórico.', max_length=20),
        ),
    ]
